.\"                                      Hey, EMACS: -*- nroff -*-
.TH SCROLLZ 1 "July  5, 2001"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
scrollz \- An advanced ircII-based IRC client
.SH SYNOPSIS
.B scrollz
.RB [ \-c
.IR chan ]
.RB [ \-p
.IR portno ]
.RB [ \-f ]
.RB [ \-F ]
.RB [ \-h
.IR host ]
.RB [ \-H
.IR host ]
.RB [ \-C
.IR name ]
.RB [ \-s ]
.RB [ \-S ]
.RB [ \-d ]
.RB [ \-q ]
.RB [ \-a ]
.RB [ \-b ]
.RB [ \-l
.IR file ]
.RB [ \-I
.IR file ]
.RB [ \-L
.IR file ]
.RB [ nickname ]
.RB [ serverlist ]
.SH DESCRIPTION
.B scrollz
is advanced IRC client based on ircII code. It adds features
normally found in ircII scripts like Toolz, PhoEniX, GargOyle or Lice.
.PP
The main difference between these scripts and
.B scrollz
is the code. Where
ircII scripts take a lot of disk and memory space and run slow,
.B scrollz
only takes a couple of extra kilobytes compared to stock ircII client
yet runs faster than any ircII script. This was accomplished by using
C code instead of ircII scripting language. This reduces memory and
CPU usage and code tends to run way faster.
.SH OPTIONS
.TP
.BI \-c " channel"
Joins channel on startup
.TP
.BI \-p " port"
.br
Default server connection port (usually 6667)
.TP
.B \-f
Your terminal uses flow controls (^S/^Q), so
.B scrollz
shouldn't
.TP
.B \-F
Your terminal doesn't use flow control (default)
.TP
.BI \-h,\-H " host"
Use host as source address (for virtual hosting)
.TP
.BI \-C " name"
Cloak process as name
.TP
.B \-S/\-s
Do/don't use separate server processes (ircio)
.TP
.B \-d
Runs
.B scrollz
in "dumb" terminal mode
.TP
.B \-q
Does not load .scrollzrc or .ircquick
.TP
.B \-a
Adds default servers and command line serves to server list
.TP
.B \-b
Load .scrollzrc before connecting to a server
.TP
.BI \-l " file"
Loads file in place of your .scrollzrc
.TP
.BI \-I " file"
Loads file in place of your .ircquick
.TP
.BI \-L " file"
Loads file in place of your .scrollz and expands $ expandos
.TP
.B \-\-help
Show summary of options.
.SH ENVIRONMENT
.TP
.B IRCNICK
The nickname to use (defaults to your username)
.TP
.B IRCNAME
The realname to use (defaults to
.I /etc/passwd
real name field)
.TP
.B IRCUMODE
The user mode to use
.TP
.B IRCPATH
The path for loading files (defaults to 
.IR ~/.ScrollZ:/usr/share/scrollz/script:. )
.TP
.B IRCSERVER
The IRC server(s) to use
.TP
.B IRCLIB
The path for ScrollZ helpfiles/scripts/translations/docs (defaults to
.IR /usr/share/scrollz )
.TP
.B HOME
Overrides your home directory in
.I /etc/passwd
.TP
.B TERM
The terminal type to use
.SH NOTES
.PP
The nickname is limited to 9 characters on many IRC networks.
.PP
The server list is a whitespace-separated list of server names.
.SH AUTHOR
This manual page was written by Mike Markley <mike@markley.org>,
for the Debian GNU/Linux system (but may be used by others).
